version: '3.8'

services:
 mysql:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: tweeter
   MYSQL_USER: test
   MYSQL_PASSWORD: secret
   MYSQL_ROOT_PASSWORD: secret
  volumes:
   - ./mysql:/var/lib/mysql

# docker-compose up
# will pull in mysql and run the image with accessible via port 3306